// Generated by `bun init`

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export default path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}


import type { Fetcher } from "@cloudflare/workers-types";

declare global {
  interface BunaCloudflareWorkerEnv {
    ASSETS: Fetcher;
    MY_BINDING: MyBindingType;
    // add whatever bindings you actually provide in your wrangler/manifest
  }
}

export { };