import { join, dirname } from "node:path";
import { mkdir, writeFile, rm } from "node:fs/promises";
import { note } from "@clack/prompts";
import { DEFAULTS } from "../constants.js";
import type { ScaffoldOptions } from "../types.js";
import logoSvg from "../public/logo-svg.js";

export async function scaffoldBaseTemplate(opts: ScaffoldOptions) {
  const files = buildBaseTemplateFiles(opts);

  for (const [relPath, content] of Object.entries(files)) {
    const target = join(opts.dir, relPath);
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, content, "utf8");
  }

  // clean possible existing .opaca from previous attempts
  await rm(join(opts.dir, ".opaca"), {
    recursive: true,
    force: true,
  }).catch(() => { });

  note(`Project created at ${opts.dir}`, "Files written");
}

function buildBaseTemplateFiles(opts: ScaffoldOptions): Record<string, string> {
  const isCloudflare = opts.runtime === "cloudflare";

  const pkg = {
    name: opts.name,
    version: "0.1.0",
    private: true,
    type: "module",
    scripts: {
      "opaca:prepare": "opaca prepare --config opaca.config.ts",
      dev: "bun run opaca:prepare && bun --hot src/entry.ts",
      build: "bun run opaca:prepare && bun run .opaca/build.ts",
      ...(isCloudflare
        ? {
          "deploy:cf":
            "NODE_ENV=production bun run build --runtime cloudflare && wrangler deploy",
        }
        : {}),
      "check-types": "tsc --noEmit",
    },
    dependencies: {
      "bun-plugin-tailwind": DEFAULTS.bunTailwindPlugin,
      react: DEFAULTS.react,
      "react-dom": DEFAULTS.reactDom,
      tailwindcss: DEFAULTS.tailwind,
      opaca: DEFAULTS.opaca,
    } as Record<string, string>,
    devDependencies: {
      "opaca-dev": DEFAULTS.opacaDev,
      "opaca-devtools": DEFAULTS.opacaDevtools,
      "@types/react": DEFAULTS.typesReact,
      "@types/react-dom": DEFAULTS.typesReactDom,
      "@types/bun": DEFAULTS.typesBun,
      "@cloudflare/workers-types": DEFAULTS.typesWorkers,
    } as Record<string, string>,
  };

  if (isCloudflare) {
    (pkg.devDependencies as Record<string, string>).wrangler = DEFAULTS.wrangler;
  }

  const typeEntry = isCloudflare ? "\"@cloudflare/workers-types\"" : "\"@types/bun\"";
  const tsconfig = `{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "node",
    "jsx": "react-jsx",
    "strict": true,
    "lib": ["ESNext", "DOM"],
    "types": [${typeEntry}],
    "outDir": "dist",
    "baseUrl": ".",
    "paths": {
      "@/*": ["./*"],
      "@public/*": ["./public/*"],

      "#opaca/*": [".opaca/*"],

      "opaca/runtime": [".opaca/runtime/index.js"],
      "opaca/runtime/*": [".opaca/runtime/*"]
    }
  },
  "include": ["src", ".opaca", "opaca.config.ts", "types", "bun-env.d.ts"],
  "exclude": ["dist", "node_modules"]
}
`;

  const bunEnvDts = `// Generated by create-opaca-app

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: \`\${string}.svg\`;
  export default path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}

${isCloudflare
    ? `import type { Fetcher } from "@cloudflare/workers-types";

declare global {
  interface OpacaCloudflareWorkerEnv {
    ASSETS: Fetcher;
  }
}

export {};
`
    : ""}
`;

  const opacaConfig = `import { defineConfig } from "opaca";

export default defineConfig({
  routesDir: "src/routes",
  outDir: ".opaca",
});
`;

  const entryTs = `import { serve } from "bun";
import { routes } from "#opaca/routes.generated";
import { handleRequest } from "opaca/runtime";
import { withDevtools } from "opaca-devtools";
import config from "@/opaca.config";

const devHandleRequest = withDevtools(handleRequest);

const server = serve({
  routes,
  development: process.env.NODE_ENV !== "production" && {
    // Enable browser hot reloading in development
    hmr: true,

    // Echo console logs from the browser to the server
    console: true,
  },
  fetch(req, server) {
    const env: any = {};
    const ctx = { waitUntil: (_p: Promise<any>) => {} };
    return devHandleRequest(req, env, ctx, config);
  },
});

console.log(\`🚀 Server running at \${server.url}\`);
`;

  const layoutTsx = `import "./index.css";
import React from "react";
import { DevtoolsPanel } from "opaca-devtools";

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      {children}
      <DevtoolsPanel />
    </>
  );
};

export default Layout;
`;

  const routeTsx = `import { createRoute, type RouteContext } from "opaca";
import { useState } from "react";
import logoUrl from "@public/logo.svg";

const AboutPage = createRoute((ctx: RouteContext) => {
  const [count, setCount] = useState(0);

  return (
    <main className="min-h-screen bg-[#0d0d0d] text-slate-100 flex items-center justify-center px-6">
      <div className="w-full flex justify-center flex-col gap-4 max-w-xl text-center">
        <img
          src={logoUrl}
          alt="Opaca logo"
          width={100}
          className="self-center"
        />
        {/* Intro */}
        <h1 className="text-4xl font-semibold tracking-tight mb-3">
          Welcome to <span className="text-emerald-400">opaca()</span>
        </h1>
        <p className="text-slate-400">
          Start editing{" "}
          <code className="px-1.5 py-0.5 bg-slate-800 rounded text-emerald-300">
            src/routes/index.tsx
          </code>{" "}
          to begin.
        </p>

        {/* Interactive Example */}
        <div className="mt-10 border border-slate-700 bg-slate-800/50 rounded-xl p-6 shadow-lg">
          <p className="text-xs uppercase tracking-wider text-slate-400 mb-4">
            Interactive example
          </p>

          <div className="flex flex-col gap-4 items-center justify-between">
            <span className="text-3xl font-medium tabular-nums">{count}</span>

            <button
              onClick={() => setCount((prev: number) => prev + 1)}
              className="px-4 py-2 text-sm rounded-lg border border-emerald-400/70 bg-emerald-500/80 text-slate-950 hover:bg-emerald-400 transition cursor-pointer"
            >
              Increment
            </button>
          </div>

          <button
            onClick={() => setCount(0)}
            className="block mx-auto mt-4 text-sm text-slate-400 hover:text-slate-200 transition cursor-pointer"
          >
            Reset
          </button>
        </div>

        {/* Footer */}
        <p className="mt-10 text-xs text-slate-500">
          Built using opaca() + Tailwind
        </p>
      </div>
    </main>
  );
});

AboutPage.meta = {
  title: "About - ${opts.name}",
  description: "Example about page using Opaca createRoute.",
  keywords: ["opaca", "${opts.name}", "about"],
  htmlLang: "en",
  robots: {
    index: true,
    follow: true,
  },
  canonicalUrl: "https://example.com/about",
  openGraph: {
    title: "About ${opts.name}",
    description: "Example about page using Opaca createRoute.",
    url: "https://example.com/about",
    siteName: "${opts.name}",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "About ${opts.name}",
    description: "Example about page using Opaca createRoute.",
  },
};

export default AboutPage;
`;

  const indexCss = `@import "tailwindcss";
`;

  const bunfig = `[serve.static]
plugins = ["bun-plugin-tailwind"]
env = "BUN_PUBLIC_*"

[entrypoints]
server = "src/entry.ts"
`;

  const gitignore = `# dependencies (bun install)
node_modules

# build output
out
dist
*.tgz

# code coverage
coverage
*.lcov

# logs
logs
_.log
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# dotenv environment variable files
.env
.env.development.local
.env.test.local
.env.production.local
.env.local

# caches
.eslintcache
.cache
*.tsbuildinfo

# IntelliJ based IDEs
.idea

# Finder (MacOS) folder config
.DS_Store

# Opaca artifacts
.opaca

# Cloudflare Wrangler config
.wrangler
`;

  const readme = `# ${opts.name}

A minimal ${isCloudflare ? "Cloudflare Worker" : "Bun"} app bootstrapped with opaca().

## Installation

\`\`\`bash
bun install
\`\`\`

## App scripts

| Command | Description |
| ------- | ----------- |
| \`bun run opaca:prepare\` | Cleans \`.opaca\`, runs \`opaca codegen\`, and recreates the hidden runner in \`.opaca/build.ts\`. |
| \`bun run dev\` | Runs \`opaca:prepare\` and starts the server with \`bun --hot src/entry.ts\`. |
| \`bun run build\` | Runs \`opaca:prepare\` and executes \`.opaca/build.ts\` ${isCloudflare ? "(targets Cloudflare)" : "(targets Bun)"}. |
| \`bun run check-types\` | Runs \`tsc --noEmit\` to check types. |

## Notes

- Always run \`bun run dev\` (or \`opaca dev\`) during development to regenerate \`.opaca\`.
- The Cloudflare bundle (when enabled) is emitted at \`.opaca/cloudflare\`.
`;

  const wrangler = isCloudflare
    ? `// Cloudflare Worker configuration for Opaca
{
  "name": "${opts.name}",
  "main": ".opaca/cloudflare/worker.js",
  "compatibility_date": "2024-05-01",
  "observability": { "enabled": true },
  "assets": { "binding": "ASSETS", "directory": ".opaca/cloudflare/assets", "run_worker_first": false },
  "compatibility_flags": ["nodejs_compat", "global_fetch_strictly_public"]
}
`
    : null;

  const files: Record<string, string> = {
    "package.json": JSON.stringify(pkg, null, 2) + "\n",
    "tsconfig.json": tsconfig,
    "opaca.config.ts": opacaConfig,
    "bunfig.toml": bunfig,
    ".gitignore": gitignore,
    "bun-env.d.ts": bunEnvDts,
    "README.md": readme,
    "public/logo.svg": logoSvg,
    "src/entry.ts": entryTs,
    "src/index.css": indexCss,
    "src/layout.tsx": layoutTsx,
    "src/routes/index.tsx": routeTsx,
  };

  if (wrangler) {
    files["wrangler.jsonc"] = wrangler;
  }

  return files;
}
